<a href="https://colab.research.google.com/github/eric88525/WikiSQL/blob/master/wikisql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Thu Aug 27 13:33:42 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.57       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8    11W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

# Paper
+ https://arxiv.org/pdf/1910.07179.pdf

# Get data from git

In [5]:
!git config --global user.email "eric885251@gmail.com"
!git config --global user.name 'eric88525'
from getpass import getpass
password = getpass('Password:')

!git clone https://eric88525:$password@github.com/eric88525/WikiSQL.git
%cd WikiSQL

Password:··········
Cloning into 'WikiSQL'...
remote: Enumerating objects: 99, done.
remote: Counting objects: 100% (99/99), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 340 (delta 60), reused 3 (delta 0), pack-reused 241
Receiving objects: 100% (340/340), 50.71 MiB | 53.04 MiB/s, done.
Resolving deltas: 100% (181/181), done.
/content/WikiSQL

In [13]:
!pip install -r requirements.txt
!tar xvjf data.tar.bz2

Requirement already satisfied: tqdm in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (4.41.1)
Requirement already satisfied: records in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (0.5.3)
Requirement already satisfied: babel in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3)) (2.8.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 4)) (0.8.7)
Requirement already satisfied: transformers in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5)) (3.0.2)
Collecting json_lines
  Downloading https://files.pythonhosted.org/packages/7f/0f/79c96c0d26b276c583484fe8209e5ebbb416a920309568650325f6e1de73/json_lines-0.5.0-py2.py3-none-any.whl
Requirement already satisfied: docopt in /usr/local/lib/python3.6/dist-packages (from records->-r requirements.txt (line 2)) (0.6.2)
Requirement already satisfied: tablib>=0.11.4 in /usr/local/lib/python3.6/dist-packages (from records->-r requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: openpyxl<2.5.0 in /usr/local/lib/python3.6/dist-packages (from records->-r requirements.txt (line 2)) (2.4.11)
Requirement already satisfied: SQLAlchemy; python_version >= "3.0" in /usr/local/lib/python3.6/dist-packages (from records->-r requirements.txt (line 2)) (1.3.19)
Requirement already satisfied: pytz>=2015.7 in /usr/local/lib/python3.6/dist-packages (from babel->-r requirements.txt (line 3)) (2018.9)
Requirement already satisfied: sentencepiece!=0.1.92 in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (0.1.91)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (2.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (20.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (3.0.12)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (1.18.5)
Requirement already satisfied: tokenizers==0.8.1.rc1 in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (0.8.1rc1)
Requirement already satisfied: sacremoses in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (0.0.43)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (2019.12.20)
Requirement already satisfied: dataclasses; python_version < "3.7" in /usr/local/lib/python3.6/dist-packages (from transformers->-r requirements.txt (line 5)) (0.7)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from json_lines->-r requirements.txt (line 6)) (1.15.0)
Requirement already satisfied: jdcal in /usr/local/lib/python3.6/dist-packages (from openpyxl<2.5.0->records->-r requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.6/dist-packages (from openpyxl<2.5.0->records->-r requirements.txt (line 2)) (1.0.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->transformers->-r requirements.txt (line 5)) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->transformers->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->transformers->-r requirements.txt (line 5)) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->transformers->-r requirements.txt (line 5)) (2020.6.20)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->transformers->-r requirements.txt (line 5)) (2.4.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from sacremoses->transformers->-r requirements.txt (line 5)) (0.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from sacremoses->transformers->-r requirements.txt (line 5)) (7.1.2)
Installing collected packages: json-lines
Successfully installed json-lines-0.5.0

# Analyze data

In [14]:
import json_lines
with open('data/dev.jsonl', 'rb') as f: 
   for item in json_lines.reader(f):
       print(item)

串流輸出內容已截斷至最後 5000 行。
{'phase': 2, 'table_id': '2-14294324-6', 'question': 'How many february games had a record of 29–24–9?', 'sql': {'sel': 1, 'conds': [[4, 0, '29–24–9']], 'agg': 5}}
{'phase': 2, 'table_id': '2-15198842-6', 'question': 'What numbered pick was the player from texas?', 'sql': {'sel': 1, 'conds': [[5, 0, 'texas']], 'agg': 3}}
{'phase': 2, 'table_id': '2-15127554-3', 'question': 'What is the conference record for the year of 1971?', 'sql': {'sel': 2, 'conds': [[0, 0, '1971']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14010415-1', 'question': 'When first elected was 2006, who was the delegate?', 'sql': {'sel': 2, 'conds': [[4, 0, 2006]], 'agg': 0}}
{'phase': 2, 'table_id': '2-14010415-1', 'question': 'Which was the district that had first elected greater than 2006 and is democratic?', 'sql': {'sel': 0, 'conds': [[3, 0, 'democratic'], [4, 1, 2006]], 'agg': 0}}
{'phase': 2, 'table_id': '2-14056030-2', 'question': 'Name the score for game more than 6 and before october 28', 'sql': {'sel': 3, 'conds': [[0, 1, 6], [1, 2, 28]], 'agg': 0}}
{'phase': 2, 'table_id': '2-14056030-2', 'question': 'Name the least game for october 21', 'sql': {'sel': 0, 'conds': [[1, 0, 21]], 'agg': 2}}
{'phase': 2, 'table_id': '2-14056030-2', 'question': 'Name the least game for record of 5-1-3', 'sql': {'sel': 0, 'conds': [[4, 0, '5-1-3']], 'agg': 2}}
{'phase': 2, 'table_id': '2-14056030-2', 'question': 'Name the most october for game less than 1', 'sql': {'sel': 1, 'conds': [[0, 2, 1]], 'agg': 1}}
{'phase': 2, 'table_id': '2-14056030-2', 'question': 'Name the least game for record of 1-0-2', 'sql': {'sel': 0, 'conds': [[4, 0, '1-0-2']], 'agg': 2}}
{'phase': 2, 'table_id': '2-14423756-3', 'question': 'Which Bronze is the highest one that has a Rank larger than 1, and a Nation of dominican republic, and a Total larger than 4?', 'sql': {'sel': 4, 'conds': [[0, 1, 1], [1, 0, 'dominican republic'], [5, 1, 4]], 'agg': 1}}
{'phase': 2, 'table_id': '2-14423756-3', 'question': 'Which Total is the lowest one that has a Rank smaller than 1?', 'sql': {'sel': 5, 'conds': [[0, 2, 1]], 'agg': 2}}
{'phase': 2, 'table_id': '2-14423756-3', 'question': 'Which Total is the lowest one that has a Rank smaller than 2, and a Silver smaller than 15?', 'sql': {'sel': 5, 'conds': [[0, 2, 2], [3, 2, 15]], 'agg': 2}}
{'phase': 2, 'table_id': '2-14423756-3', 'question': 'Which Silver has a Gold of 2, and a Nation of puerto rico, and a Total smaller than 12?', 'sql': {'sel': 3, 'conds': [[2, 0, 2], [1, 0, 'puerto rico'], [5, 2, 12]], 'agg': 4}}
{'phase': 2, 'table_id': '2-14184508-1', 'question': "Which Men's doubles have a Year smaller than 1960, and Men's singles of noel b. radford?", 'sql': {'sel': 3, 'conds': [[0, 2, 1960], [1, 0, 'noel b. radford']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14962245-2', 'question': 'Album of les mots had what lowest year?', 'sql': {'sel': 4, 'conds': [[2, 0, 'les mots']], 'agg': 2}}
{'phase': 2, 'table_id': '2-14001393-4', 'question': 'What team has 2000-01 as the season?', 'sql': {'sel': 1, 'conds': [[2, 0, '2000-01']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14001393-4', 'question': 'What season has a number less than 90, Mitte as the league and spvgg ruhmannsfelden as the team?', 'sql': {'sel': 2, 'conds': [[4, 2, 90], [3, 0, 'mitte'], [1, 0, 'spvgg ruhmannsfelden']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14001393-4', 'question': 'What league has a number less than 122, and least wins as the record?', 'sql': {'sel': 3, 'conds': [[4, 2, 122], [0, 0, 'least wins']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14001393-4', 'question': 'What league has most wins as the record?', 'sql': {'sel': 3, 'conds': [[0, 0, 'most wins']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14001393-4', 'question': 'What league has a number less than 1?', 'sql': {'sel': 3, 'conds': [[4, 2, 1]], 'agg': 0}}
{'phase': 2, 'table_id': '2-15062102-1', 'question': 'What is the average nominated of the composition nominated by Taioseach with an Industrial and Commercial panel less than 9, an administrative panel greater than 0, a cultural and educational panel greater than 2, and a total less than 29?', 'sql': {'sel': 6, 'conds': [[3, 2, 9], [0, 1, 0], [2, 1, 2], [7, 2, 29]], 'agg': 5}}
{'phase': 2, 'table_id': '2-15062102-1', 'question': 'What is the average administrative panel of the composition nominated by Taoiseach 0 times with a total less than 4?', 'sql': {'sel': 0, 'conds': [[6, 0, 0], [7, 2, 4]], 'agg': 5}}
{'phase': 2, 'table_id': '2-15062102-1', 'question': 'What is the highest number of nominations by Taoiseach of the composition with an administrative panel greater than 0 and an industrial and commercial panel less than 1?', 'sql': {'sel': 6, 'conds': [[0, 1, 0], [3, 2, 1]], 'agg': 1}}
{'phase': 2, 'table_id': '2-15062102-1', 'question': 'What is the average agricultural panel of the composition with a labour panel less than 6, more than 0 nominations by Taoiseach, and a total less than 4?', 'sql': {'sel': 1, 'conds': [[4, 2, 6], [6, 1, 0], [7, 2, 4]], 'agg': 5}}
{'phase': 2, 'table_id': '2-15062102-1', 'question': 'What is the total number of agriculatural panels of the composition with more than 3 National Universities of Ireland?', 'sql': {'sel': 1, 'conds': [[5, 1, 3]], 'agg': 3}}
{'phase': 2, 'table_id': '2-14271815-8', 'question': 'What was the attendance on September 28?', 'sql': {'sel': 4, 'conds': [[0, 0, 'september 28']], 'agg': 1}}
{'phase': 2, 'table_id': '2-14913233-11', 'question': 'Away result of 1-2 has what season?', 'sql': {'sel': 0, 'conds': [[5, 0, '1-2']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14913233-11', 'question': 'Round of 2r, and a Home result of 0-0 has what season?', 'sql': {'sel': 0, 'conds': [[2, 0, '2r'], [4, 0, '0-0']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14913233-11', 'question': 'Home result of 1–0, and a Away result of 0–1 involves what club?', 'sql': {'sel': 3, 'conds': [[4, 0, '1–0'], [5, 0, '0–1']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14913233-11', 'question': 'Round of 1r, and an away result of 7–1 is what season?', 'sql': {'sel': 0, 'conds': [[2, 0, '1r'], [5, 0, '7–1']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14913233-11', 'question': 'Away result of 0–3, and a Season of 1969-70 is what competition?', 'sql': {'sel': 1, 'conds': [[5, 0, '0–3'], [0, 0, '1969-70']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14913233-11', 'question': 'Away result of 1–1, and a Round of 1r, and a Season of 1967-68 involves what club?', 'sql': {'sel': 3, 'conds': [[5, 0, '1–1'], [2, 0, '1r'], [0, 0, '1967-68']], 'agg': 0}}
{'phase': 2, 'table_id': '2-13810103-1', 'question': 'what was the nominee of best musical', 'sql': {'sel': 3, 'conds': [[2, 0, 'best musical']], 'agg': 0}}
{'phase': 2, 'table_id': '2-13810103-1', 'question': 'what year was michele assaf nominated', 'sql': {'sel': 0, 'conds': [[3, 0, 'michele assaf']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14886978-1', 'question': 'What was the highest pick for a player from a school or club team of Arkansas?', 'sql': {'sel': 1, 'conds': [[4, 0, 'arkansas']], 'agg': 1}}
{'phase': 2, 'table_id': '2-14177667-3', 'question': 'How many Golds did Rank 10 get, with a Bronze larger than 2?', 'sql': {'sel': 2, 'conds': [[0, 0, '10'], [4, 1, 2]], 'agg': 3}}
{'phase': 2, 'table_id': '2-14177667-3', 'question': "What rank is Turkmenistan, who had 0 silver's and Less than 2 golds?", 'sql': {'sel': 0, 'conds': [[3, 0, 0], [2, 2, 2], [1, 0, 'turkmenistan']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14177667-3', 'question': "What's the biggest Bronze that has less than 0 Silvers?", 'sql': {'sel': 4, 'conds': [[3, 2, 0]], 'agg': 1}}
{'phase': 2, 'table_id': '2-14177667-3', 'question': "What is the total Gold's less than 0?", 'sql': {'sel': 5, 'conds': [[2, 2, 0]], 'agg': 3}}
{'phase': 2, 'table_id': '2-14385107-2', 'question': 'What city is the School, Highland, in that ranks less than 8 and had its first title before 1980 and its last title later than 1960?', 'sql': {'sel': 3, 'conds': [[0, 2, 8], [5, 2, 1980], [6, 1, 1960], [2, 0, 'highland']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14385107-2', 'question': 'What city is the school that had less than 17 titles in boys basketball with the last title being after 2005?', 'sql': {'sel': 3, 'conds': [[1, 2, 17], [6, 1, 2005], [4, 0, 'boys basketball']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14385107-2', 'question': 'What is the highest rank for the boys swimming team in Albuquerque?', 'sql': {'sel': 0, 'conds': [[4, 0, 'boys swimming'], [3, 0, 'albuquerque']], 'agg': 1}}
{'phase': 2, 'table_id': '2-14385107-2', 'question': "What is the total rank number for Los Alamos' girls cross country?", 'sql': {'sel': 0, 'conds': [[2, 0, 'los alamos'], [4, 0, 'girls cross country']], 'agg': 3}}
{'phase': 2, 'table_id': '2-14835245-1', 'question': 'What capital has an S.Number under 7, and a Name of janapada of Punia?', 'sql': {'sel': 4, 'conds': [[0, 2, 7], [1, 0, 'punia']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14835245-1', 'question': 'What king has an S. number over 1 and a number of villages of 600?', 'sql': {'sel': 2, 'conds': [[0, 1, 1], [3, 0, 600]], 'agg': 0}}
{'phase': 2, 'table_id': '2-14835245-1', 'question': 'What is the average number of villages with a name of janapada of Punia?', 'sql': {'sel': 3, 'conds': [[1, 0, 'punia']], 'agg': 5}}
{'phase': 2, 'table_id': '2-14835245-1', 'question': 'What is the highest S number with a capital of Shekhsar?', 'sql': {'sel': 0, 'conds': [[4, 0, 'shekhsar']], 'agg': 1}}
{'phase': 2, 'table_id': '2-15085862-1', 'question': 'What is the highest round number for the player who came from team Missouri?', 'sql': {'sel': 0, 'conds': [[4, 0, 'missouri']], 'agg': 1}}
{'phase': 2, 'table_id': '2-15085862-1', 'question': 'What is the total number of rounds that had draft pick 97, duncan mccoll?', 'sql': {'sel': 0, 'conds': [[2, 0, 'duncan mccoll'], [1, 2, 97]], 'agg': 3}}
{'phase': 2, 'table_id': '2-14265951-2', 'question': 'What opponent uses the method of decision and a 5-3 record?', 'sql': {'sel': 2, 'conds': [[3, 0, 'decision'], [1, 0, '5-3']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14265951-2', 'question': 'What round has the highest Res loss, and a time of 40:00?', 'sql': {'sel': 5, 'conds': [[0, 0, 'loss'], [6, 0, '40:00']], 'agg': 1}}
{'phase': 2, 'table_id': '2-14028934-3', 'question': 'Who visited on April 29?', 'sql': {'sel': 3, 'conds': [[0, 0, 'april 29']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14028934-3', 'question': 'When did Montreal visit and have a score of 1-4?', 'sql': {'sel': 0, 'conds': [[3, 0, 'montreal'], [2, 0, '1-4']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14028934-3', 'question': 'What was the score on April 25?', 'sql': {'sel': 2, 'conds': [[0, 0, 'april 25']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14028934-3', 'question': 'What was the score on May 3?', 'sql': {'sel': 2, 'conds': [[0, 0, 'may 3']], 'agg': 0}}
{'phase': 2, 'table_id': '2-13909437-13', 'question': 'What is the School/Junior/Club Group (Association) that has a Round bigger than 6, and a Place of winger, and a Player of evgeny afanasiev?', 'sql': {'sel': 4, 'conds': [[0, 1, 6], [2, 0, 'winger'], [1, 0, 'evgeny afanasiev']], 'agg': 0}}
{'phase': 2, 'table_id': '2-13909437-13', 'question': 'What is the School/Junior/Club Group (Class) that has a Nationality of canada, and a Place of goalie?', 'sql': {'sel': 4, 'conds': [[3, 0, 'canada'], [2, 0, 'goalie']], 'agg': 0}}
{'phase': 2, 'table_id': '2-13909437-13', 'question': 'What is the Nationality for alexandre jacques?', 'sql': {'sel': 3, 'conds': [[1, 0, 'alexandre jacques']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15100419-6', 'question': 'What is the highest Pick that is wide receiver with overall of 29?', 'sql': {'sel': 1, 'conds': [[4, 0, 'wide receiver'], [2, 0, 29]], 'agg': 1}}
{'phase': 2, 'table_id': '2-15100419-6', 'question': 'What is the lowest Round with Overall of 247 and pick less than 41?', 'sql': {'sel': 0, 'conds': [[2, 0, 247], [1, 2, 41]], 'agg': 2}}
{'phase': 2, 'table_id': '2-15100419-6', 'question': 'What is the Position with a round 3 pick for r. jay soward?', 'sql': {'sel': 4, 'conds': [[0, 2, 3], [3, 0, 'r. jay soward']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15100419-6', 'question': 'What is the average Round for wide receiver r. jay soward and Overall smaller than 29?', 'sql': {'sel': 0, 'conds': [[4, 0, 'wide receiver'], [3, 0, 'r. jay soward'], [2, 2, 29]], 'agg': 5}}
{'phase': 2, 'table_id': '2-14342480-4', 'question': 'Which Points is the lowest one that has Touchdowns smaller than 2, and an Extra points of 7, and a Field goals smaller than 0?', 'sql': {'sel': 5, 'conds': [[1, 2, 2], [2, 0, 7], [3, 2, 0]], 'agg': 2}}
{'phase': 2, 'table_id': '2-14342480-4', 'question': 'How many Touchdowns have a Player of rolla bigelow, and an Extra points smaller than 0?', 'sql': {'sel': 1, 'conds': [[0, 0, 'rolla bigelow'], [2, 2, 0]], 'agg': 4}}
{'phase': 2, 'table_id': '2-1507712-1', 'question': 'Which Longi- tude is on jun 6?', 'sql': {'sel': 0, 'conds': [[6, 0, 'jun 6']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1507712-1', 'question': 'When has a Korean name ² of 청명 (清明) cheongmyeong?', 'sql': {'sel': 6, 'conds': [[4, 0, '청명 (清明) cheongmyeong']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1507712-1', 'question': 'WHICH Vietnamese name has a Chinese name ¹ of 芒種 (芒种) mángzhòng?', 'sql': {'sel': 5, 'conds': [[2, 0, '芒種 (芒种) mángzhòng']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1507712-1', 'question': 'WHICH Usual translation is on jun 21?', 'sql': {'sel': 1, 'conds': [[6, 0, 'jun 21']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1507712-1', 'question': 'Which Japanese name has a Korean name ² of 경칩 (驚蟄) gyeongchip?', 'sql': {'sel': 3, 'conds': [[4, 0, '경칩 (驚蟄) gyeongchip']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1507712-1', 'question': 'WHich Usual translation is on sep 23?', 'sql': {'sel': 1, 'conds': [[6, 0, 'sep 23']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14670399-1', 'question': 'What is the average Week for the game at three rivers stadium, with a Record of 3–2?', 'sql': {'sel': 0, 'conds': [[3, 0, 'three rivers stadium'], [6, 0, '3–2']], 'agg': 5}}
{'phase': 2, 'table_id': '2-14670399-1', 'question': 'What is the result of the game at three rivers stadium with a Record of 6–3?', 'sql': {'sel': 5, 'conds': [[3, 0, 'three rivers stadium'], [6, 0, '6–3']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14670399-1', 'question': 'What is the earliest week that shows a record of 8–5?', 'sql': {'sel': 0, 'conds': [[6, 0, '8–5']], 'agg': 2}}
{'phase': 2, 'table_id': '2-14670399-1', 'question': 'What is the record of the game that has a result of w 45–17?', 'sql': {'sel': 6, 'conds': [[5, 0, 'w 45–17']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14670399-1', 'question': 'What week that shows a game record of 0–1?', 'sql': {'sel': 0, 'conds': [[6, 0, '0–1']], 'agg': 5}}
{'phase': 2, 'table_id': '2-13599687-6', 'question': 'Which driver has less than 37 wins and at 14.12%?', 'sql': {'sel': 2, 'conds': [[3, 2, 37], [4, 0, '14.12%']], 'agg': 5}}
{'phase': 2, 'table_id': '2-13599687-6', 'question': 'Which driver has 162 entries?', 'sql': {'sel': 0, 'conds': [[2, 0, 162]], 'agg': 0}}
{'phase': 2, 'table_id': '2-13599687-6', 'question': 'Which season did jackie stewart enter with entries less than 215?', 'sql': {'sel': 1, 'conds': [[2, 2, 215], [0, 0, 'jackie stewart']], 'agg': 0}}
{'phase': 2, 'table_id': '2-13998897-1', 'question': 'How many ERP W is it that has a Call sign of w273bs?', 'sql': {'sel': 3, 'conds': [[0, 0, 'w273bs']], 'agg': 4}}
{'phase': 2, 'table_id': '2-13998897-1', 'question': 'Which City of license has a Frequency MHz smaller than 100.9, and a ERP W larger than 100?', 'sql': {'sel': 2, 'conds': [[1, 2, 100.9], [3, 1, 100]], 'agg': 0}}
{'phase': 2, 'table_id': '2-13998897-1', 'question': 'What is the number of Frequency MHz in woodstock, georgia?', 'sql': {'sel': 1, 'conds': [[2, 0, 'woodstock, georgia']], 'agg': 4}}
{'phase': 2, 'table_id': '2-13998897-1', 'question': 'What is the lowest ERP W of  w223bp?', 'sql': {'sel': 3, 'conds': [[0, 0, 'w223bp']], 'agg': 2}}
{'phase': 2, 'table_id': '2-14076980-4', 'question': 'What was the highest points where there were less than 2 drawn and the games were less than 6?', 'sql': {'sel': 4, 'conds': [[1, 2, 2], [0, 2, 6]], 'agg': 1}}
{'phase': 2, 'table_id': '2-14607-5', 'question': 'What is the license plate code for the country with an area of 784?', 'sql': {'sel': 2, 'conds': [[6, 0, 784]], 'agg': 0}}
{'phase': 2, 'table_id': '2-14607-5', 'question': 'What is the country seat for the license plate code 5c?', 'sql': {'sel': 1, 'conds': [[2, 0, '5c']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1408397-2', 'question': 'Which Pada 3 has a Pada 1 of टे te?', 'sql': {'sel': 3, 'conds': [[1, 0, 'टे te']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1408397-2', 'question': 'which Pada 4 has a Pada 2 of थ tha?', 'sql': {'sel': 4, 'conds': [[2, 0, 'थ tha']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1408397-2', 'question': 'which Pada 3 has a Pada 2 of चे che?', 'sql': {'sel': 3, 'conds': [[2, 0, 'चे che']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1408397-2', 'question': 'What is the Name of ङ ng/na?', 'sql': {'sel': 0, 'conds': [[3, 0, 'ङ ng/na']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1408397-2', 'question': 'What kind of Pada 4 has a Pada 1 of खी ju/khi?', 'sql': {'sel': 4, 'conds': [[1, 0, 'खी ju/khi']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1408397-2', 'question': 'What kind of Pada 1 has a Pada 2 of सा sa?', 'sql': {'sel': 1, 'conds': [[2, 0, 'सा sa']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15061543-2', 'question': 'Name the points classification for stage of 18b', 'sql': {'sel': 3, 'conds': [[0, 0, '18b']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15061543-2', 'question': 'Name the points classification of stage 16', 'sql': {'sel': 3, 'conds': [[0, 0, '16']], 'agg': 0}}
{'phase': 2, 'table_id': '2-1389609-1', 'question': 'Total Population (2011 est) larger than 30,262,610, and a Hindu total of 63,718 involves what country?', 'sql': {'sel': 1, 'conds': [[2, 1, '30,262,610'], [4, 0, '63,718']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15278607-2', 'question': 'What is the round of the match with Emanuel Newton as the opponent?', 'sql': {'sel': 5, 'conds': [[2, 0, 'emanuel newton']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15278607-2', 'question': 'What is the location of the match with Aron Lofton as the opponent?', 'sql': {'sel': 7, 'conds': [[2, 0, 'aron lofton']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15278607-2', 'question': 'What is the location of the match with an event of ecc 8: comeback?', 'sql': {'sel': 7, 'conds': [[4, 0, 'ecc 8: comeback']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15278607-2', 'question': 'Who is the opponent of the match with a win result and a time of 3:02?', 'sql': {'sel': 2, 'conds': [[0, 0, 'win'], [6, 0, '3:02']], 'agg': 0}}
{'phase': 2, 'table_id': '2-15278607-2', 'question': 'What is the method of the match with 1 round and a time of 1:58?', 'sql': {'sel': 3, 'conds': [[5, 0, 1], [6, 0, '1:58']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14656139-2', 'question': 'How many people attended the game on September 19, 1976?', 'sql': {'sel': 5, 'conds': [[1, 0, 'september 19, 1976']], 'agg': 3}}
{'phase': 2, 'table_id': '2-14656139-2', 'question': 'What is the lowest week number where they played against the Detroit Lions?', 'sql': {'sel': 0, 'conds': [[2, 0, 'detroit lions']], 'agg': 2}}
{'phase': 2, 'table_id': '2-14656139-2', 'question': 'What is the average attendance for the game on September 26, 1976?', 'sql': {'sel': 5, 'conds': [[1, 0, 'september 26, 1976']], 'agg': 5}}
{'phase': 2, 'table_id': '2-14655866-1', 'question': 'Which pick has a school/club team that is kentucky?', 'sql': {'sel': 1, 'conds': [[4, 0, 'kentucky']], 'agg': 0}}
{'phase': 2, 'table_id': '2-14655866-1', 'question': 'Which player is it that has a pick of 147?', 'sql': {'sel': 2, 'conds': [[1, 0, '147']], 'agg': 0}}

# Commit

In [17]:
!git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   requirements.txt

no changes added to commit (use "git add" and/or "git commit -a")

In [15]:
!git commit -m 'add requirement'  # commit in Colab
!git push origin master          # push to github

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
	modified:   requirements.txt

no changes added to commit
Everything up-to-date